# Generated by Django 5.2.4 on 2025-08-02 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.CharField(choices=[('daily', '日榜'), ('weekly', '周榜'), ('monthly', '月榜'), ('all_time', '总榜')], max_length=20, verbose_name='排行榜类型')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='分数')),
                ('vocabulary_level', models.CharField(max_length=20, verbose_name='词汇水平')),
                ('rank_position', models.IntegerField(verbose_name='排名位置')),
                ('test_count', models.IntegerField(default=1, verbose_name='测试次数')),
                ('period_start', models.DateField(verbose_name='统计开始日期')),
                ('period_end', models.DateField(verbose_name='统计结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '排行榜',
                'verbose_name_plural': '排行榜',
                'db_table': 'rankings',
                'unique_together': {('user', 'ranking_type', 'period_start')},
            },
        ),
    ]
