# Generated by Django 5.2.4 on 2025-08-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='单词')),
                ('phonetic', models.CharField(blank=True, max_length=100, verbose_name='音标')),
                ('translation', models.TextField(verbose_name='中文释义')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('professional', '专业级')], max_length=20, verbose_name='难度等级')),
                ('part_of_speech', models.CharField(blank=True, max_length=50, verbose_name='词性')),
                ('example_sentence', models.TextField(blank=True, verbose_name='例句')),
                ('frequency', models.IntegerField(default=0, verbose_name='使用频率')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '词汇',
                'verbose_name_plural': '词汇',
                'db_table': 'vocabulary',
            },
        ),
    ]
