# Generated by Django 5.2.4 on 2025-08-02 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('choice', '选择题'), ('fill_blank', '填空题'), ('matching', '匹配题')], max_length=20, verbose_name='题目类型')),
                ('question_text', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(verbose_name='选项')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, verbose_name='解释')),
                ('difficulty', models.CharField(max_length=20, verbose_name='难度等级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('vocabulary', '词汇量测试'), ('speed', '速度测试'), ('accuracy', '准确度测试')], max_length=20, verbose_name='测试类型')),
                ('difficulty', models.CharField(max_length=20, verbose_name='难度等级')),
                ('total_questions', models.IntegerField(verbose_name='总题目数')),
                ('correct_answers', models.IntegerField(verbose_name='正确答案数')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='得分')),
                ('vocabulary_level', models.CharField(max_length=20, verbose_name='词汇水平')),
                ('duration', models.IntegerField(verbose_name='测试时长(秒)')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '测试记录',
                'verbose_name_plural': '测试记录',
                'db_table': 'test_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
