# Generated by Django 5.2.4 on 2025-08-02 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_study_time', models.IntegerField(default=0, verbose_name='总学习时长(分钟)')),
                ('total_words_learned', models.IntegerField(default=0, verbose_name='已学单词数')),
                ('total_tests_taken', models.IntegerField(default=0, verbose_name='总测试次数')),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='平均分数')),
                ('highest_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='最高分数')),
                ('consecutive_days', models.IntegerField(default=0, verbose_name='连续学习天数')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='最后学习日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户统计',
                'verbose_name_plural': '用户统计',
                'db_table': 'user_statistics',
            },
        ),
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('study_time', models.IntegerField(default=0, verbose_name='学习时长(分钟)')),
                ('tests_taken', models.IntegerField(default=0, verbose_name='测试次数')),
                ('words_learned', models.IntegerField(default=0, verbose_name='学习单词数')),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='平均分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'db_table': 'daily_statistics',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='是否掌握')),
                ('review_count', models.IntegerField(default=0, verbose_name='复习次数')),
                ('last_review_date', models.DateTimeField(blank=True, null=True, verbose_name='最后复习时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabulary', verbose_name='词汇')),
            ],
            options={
                'verbose_name': '词汇进度',
                'verbose_name_plural': '词汇进度',
                'db_table': 'vocabulary_progress',
                'unique_together': {('user', 'vocabulary')},
            },
        ),
    ]
